default: &default
  timeout: 5000
  adapter: postgresql
  encoding: utf8
  database: cosmosray_development
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: cosmosray_test

production:
  <<: *default